### ISSUE TITLE
e2e TEST | Error Handling

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1654]
### Description

review the current testing suite to consolidate coverage on the new error handling functionality

### User Story

As a developer I would like to include e2e coverage on the updated error handling functionality

### Acceptance Criteria

Testing coverage includes
- [x] expects error count in alert https://github.com/GSA/px-benefit-finder/issues/1511
- [x] expects a list of links to the fields that have errors https://github.com/GSA/px-benefit-finder/issues/1512
- [x] expects validation of errors removes error styles and error description in list https://github.com/GSA/px-benefit-finder/issues/1512
- [ ] expects to handle radio group fieldsets
- [x] expects to handle error label content coverrides

**Comment by nehemiah-abuga** [comment]
80 % complete..Working on radio group and label content
