### ISSUE TITLE
Plan unmoderated testing for UXR/KPI tracking

### ISSUE THREAD

**Issue by Ndoyle118** [GSA/px-benefit-finder#352]
In order to generate data for and track our progress related to the KPI that 75% of users in user research sessions will understand the purpose and function of the tool from the first page, I need to collaborate with Nick Pistone (Data Analytics/KPIs) to develop a plan to incorporate this into user research. 

- [x] Nick D piloted an open-ended question in v1/v2 Moderated Usability Testing to generate user feedback on the start page
- [x] Nick D + Nick Pistone met on 8/8 to discuss the feedback we've received and further refine key questions to generate usable data
- [x] Nick D + Nick P recommend using unmoderated sessions to get quick feedback from a larger set of users (~20) 
- [x] Nick D. will set up unmoderated, shorter tests with ~20 users to get feedback on only the starting page of BEARS v2
