### ISSUE TITLE
Accessibility "roadmap" projects

### ISSUE THREAD

**Issue by amycole501** [GSA/px-benefit-finder#670]
**Review of initial audit-confirming level[ B and C]**(https://docs.google.com/document/d/1YLwn3_N9XeeluZNerTojZTc71C1sDhNPDE2OrkU7GOE/edit?usp=sharing) issues are completed

- [ ] Audit using Axe Dev Tools Pro to check code

- [ ] Checking against WCAG 2.2 success criteria (new in October 2023)

**Auditing for mobile accessibility** 

- [ ] - iPhone
- [ ] - Android
- [ ] - Checking both horizontal and vertical orientations

**Rechecking once live; auditing using:**

- [ ] 
- [ ] NVDA
- [ ] Narrator (PC)
- [ ] VoiceOver (Mac)

**CMS accessibility audit**

Provide accessibility training materials for:

- [ ] Design
- [ ] Content
- [ ] Developers
- [ ] PM/project management

**Comment by fongcindy** [comment]
@angelina-smith Any updates on this ticket? Should we shift this to the backlog?
