### ISSUE TITLE
Update release script

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#865]
## Background

We have some incoming work that will require an update to the release task. 

Release Task: https://github.com/GSA/px-benefit-finder/blob/main/.github/workflows/release-action.yml
Incoming Work: https://github.com/GSA/px-benefit-finder/pull/851

Two (2) items to make note of from incoming work
- Running `npm run build` will output a `dist` directory with the necessary files to contribute upstream.
- We updated to run concurrent tasks in pipeline when test running Cypress Tests, this allows us to run `component` and `e2e` test in the pipeline without having to pass auth credentials
- We updated to use the node engine configured in `package.json` rather than setting it based on `.nvmrc`

## Tasks

- [ ] include `./benefit-finder/dist` directory with `usagov_benefit_finder/`
- [ ] use package.json engine config to set node version (https://github.com/GSA/px-benefit-finder/blob/main/.github/workflows/release-action.yml#L75-L77)
- [ ] review `Building & Deploying Storybook App to Dev Env` and `Cypres Testing` steps
(https://github.com/GSA/px-benefit-finder/blob/main/.github/workflows/release-action.yml#L62-L106) to see if it would be better to use the updated Cypress action steps (https://github.com/GSA/px-benefit-finder/blob/migrate-vite/.github/workflows/cypress.yml#L38C1-L39C43)
- [ ] review rest of steps and determine if we can make other improvements

**Comment by scottqueen-bixal** [comment]
I noticed that we are deploying storybook to the dev env during release, seems like we would want to move away from that with our gitflow going through dev now, 

https://github.com/GSA/px-benefit-finder/blob/dev/.github/workflows/release-action.yml#L62-L92

**Comment by scottqueen-bixal** [comment]
Scott to talk with Amy before moving forward

**Comment by scottqueen-bixal** [comment]
client decided they did not need the dist in the module contribution
