### ISSUE TITLE
Run e2e against usa.gov static public site

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#879]
## Background

We are noticing that some content changes made on usagov are impacting functionality on our application.  This appears to be outside our code, so we are thinking about implementing a few e2e tests and run them on a cron to track potential breaks.

example: https://github.com/GSA/px-benefit-finder/issues/877

## Tasks

- [x] determine if cypress can run agains usagov public static site
- [x] create a two (2) test that can watch for changes 1) to breadcrumbs and 2) mobile menu access

Test(s)

- [x] 1. confirm that mobile menu works and a user can navigate to each of our paths, both en/es

`/benefit-finder`
`/death`
`/retirement`
`/disability`

- [x] 2. ensure that benefit-finder card appears on https://www.usa.gov/benefits and a user can access `/benefit-finder` by clicking this card

## Acceptance Criteria

- [x] e2e test running agains usa.gov on daily cron in github actions

**Comment by nehemiah-abuga** [comment]
Test automation in progress
https://github.com/GSA/px-benefit-finder/compare/dev...879-cypress-e2e-usagov-static-site?expand=1

**Comment by nehemiah-abuga** [comment]
Checked final code that runs the test. Scott working on the cron job
