### ISSUE TITLE
Review release manual QA process

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#884]
## Background

While we gain confidence in the release cycle, we are going to be making changes to improve and streamline the action.  While we are making these changes, when we have a release we may want to manually ensure the bundled package included works as expected before creating a release PR to USAGov.

## TODO

- [x] Review the steps outlined in our developer guidance documentation https://docs.google.com/document/d/1PjE_lkX62PKC_nc8wl5ZFWF9sHPFL3vHYpA1YTXPMqw/edit#heading=h.v42bp1n6jspw
- [x] Attempt each step
- [x] Update or clarify any steps that may be incorrect or need additional context

## Acceptance Criteria

- [x] Developers confirm that the process has been successfully completed in local environment, leave comment on this ticket

**Comment by nehemiah-abuga** [comment]
I was able to go through the steps successfully
