### ISSUE TITLE
create shared calendar for release cycle

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#897]
## Background

We have a new release cycle. We would like to share a calendar that is accessible to the Benefit Finder team and potentially its stakeholders.

We should consider Google Calendar since it can be shared and managed to both GSA and BX stakeholders.

Our release cycle document
https://docs.google.com/spreadsheets/d/1-Go0_iodk0WEDSQ-jCgsy8EOLuuLHOOo0iQDpzX_0ZA/edit#gid=1070460332

USAGov PX webops has this operation https://calendar.google.com/calendar/u/1/r/settings/calendar/Y183NjI2OGFjNjBiYzdkNmMyYjZmMDVjYjhhMWMyNTA1MzhjZTQ2ZDliNTUzOTNiNDc2OGUxYzk2YTJlNDJiYmNkQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20

![Image](https://github.com/GSA/px-benefit-finder/assets/37077057/32a470d5-3394-4f6e-9cad-2b9783026174)

Combining our release calendar with the USAGov PX webops calendar, team members should have a clear view of upstream workflow for planning and communication.

## Task

1. create a calendar with the deployment release cycle milestones
2. include current team members
3. include with onboarding
4. share calendar with benefit-finder team

## Acceptance Criteria

- [x] benefit finder team is able to subscribe to the Benefit Finder WebOps calendar 

The calendar includes:

- [x] major/minor release windows, every 7th Wednesday following the 6th sprint closing from 2pm-4pm
- [x] patch release windows every 3rd Wednesday following the sprint closing

The following roles can manage:

PM, PO, Tech Lead

**Comment by EnriqueOrt** [comment]
Share Calendar created in G-suite - working on configuration and access 
https://calendar.google.com/calendar/u/0/r/settings/calendar/Y181YTJlNmQxOTcxMGU3YThiMjg1NjVjN2QzZWMzMzc0MTBjY2M4ZGIxYzFhMTVlOThkNDRlMmQ1ODc0MDg4Yjg3QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20

**Comment by EnriqueOrt** [comment]
Acceptance criteria items scheduled on shared calendar - access and sharing granted to PM, PO, Tech Lead. 
Benefit Finder team will have to subscribe to calendar to see side-by-side view/milestones. 

@scottqueen-bixal for vis and review
